name: build

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  export:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Monologue export
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      
      - name: Install wine
        id: wine_install
        run: |
          sudo apt-get update
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
      
      - name: Export game
        id: export
        uses: firebelley/godot-export@v5.1.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.0/Godot_v4.0-stable_export_templates.tpz
          relative_project_path: ./
          relative_export_path: ./builds/
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
      
      - name: Create release
        uses: ncipollo/release-action@v1.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          name: Monologue ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.build_directory }}/**/*
          replacesArtifacts: true
          prerelease: ${{ contains(fromJSON('["dev", "pre", "alpha", "beta", "rc"]'), github.event_name) }}
          
  
  publish:
    permissions: read-all
    needs: export
    name: Publish to Itch.io 🚀
    runs-on: ubuntu-latest
    steps:
      - name: (Windows) Publish build on Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
            BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY  }}
            CHANNEL: windows
            ITCH_GAME: monologue
            ITCH_USER: atomic-junky
            PACKAGE: ./builds/
            VERSION: $GITHUB_REF_NAME:1