on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'


jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Monologue Publish
    steps:
      - name: Wait for export to complete
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Monologue export'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
      
      - name: (Windows) Publish build on Itch.io
        uses: manleydev/butler-publish-itchio-action@master
        env:
            BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
            CHANNEL: windows
            ITCH_GAME: monologue
            ITCH_USER: atomic-junky
            PACKAGE: ./builds/
            VERSION: $GITHUB_REF_NAME:1